### PR TITLE
feat: use field/label selector parser from apimachinery

### PR DESCRIPTION
**Pull request by adityathebe**
resolves: https://github.com/flanksource/duty/issues/585

### CODE REVIEW

**Comment by yashmehrotra** [comment]
@adityathebe Is this change backward compatible with current implementation ?

**Comment by adityathebe** [comment]
> @adityathebe Is this change backward compatible with current implementation ?

everything else should work fine apart from the `a=` syntax for `exists` query. That's not supported by the apimachinery's label parser.

**Comment by yashmehrotra** [comment]
> everything else should work fine apart from the `a=` syntax for `exists` query. That's not supported by the apimachinery's label parser.

We use `labelSelector: kustomize.fluxcd.io/name` to fetch Configs which are managed by flux

**Comment by adityathebe** [comment]
@yashmehrotra oh that's the syntax. That should be easy to support. Let me make that change.

**Comment by adityathebe** [comment]
need to make some changes on this PR after [this](https://github.com/flanksource/mission-control/pull/928) is merged.

**Pull request merged**
