### PR TITLE
feat: aws view for config_items

### PR DESCRIPTION
**Pull request by yashmehrotra**

### CODE REVIEW

**Comment by moshloop** [comment]
I think we should use the existing configs view as base and then add ontop of that

**Comment by moshloop** [comment]
@yashmehrotra  https://github.com/flanksource/duty/blob/main/views/006_config_views.sql#L3 has more than just the default columns

**Comment by moshloop** [comment]
So maybe we change the select to be configs rather than config_items ?

**Comment by yashmehrotra** [comment]
@moshloop Makes sense, have updated the query

**Pull request merged**
